
'use server';
/**
 * @fileOverview A Genkit flow to create a user subscription via Mercado Pago.
 *
 * - createUserSubscription - Creates a subscription for a user.
 * - CreateUserSubscriptionInput - The input type for the flow.
 * - CreateUserSubscriptionOutput - The return type for the flow.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore, Timestamp } from 'firebase-admin/firestore';
import { adminApp } from '@/lib/firebase-admin';

const CreateUserSubscriptionInputSchema = z.object({
  token: z.string().describe("The card token generated by Mercado Pago's frontend."),
  issuer_id: z.string().describe("The card issuer ID."),
  payment_method_id: z.string().describe("The payment method ID (e.g., 'visa')."),
  installments: z.number().describe("The number of installments."),
  payer_email: z.string().email().describe("The email of the user paying."),
});
export type CreateUserSubscriptionInput = z.infer<typeof CreateUserSubscriptionInputSchema>;

const CreateUserSubscriptionOutputSchema = z.object({
  success: z.boolean(),
  subscriptionId: z.string().optional(),
  error: z.string().optional(),
});
export type CreateUserSubscriptionOutput = z.infer<typeof CreateUserSubscriptionOutputSchema>;


const getFirebaseUserByEmail = async (email: string) => {
    try {
        const auth = getAuth(adminApp);
        return await auth.getUserByEmail(email);
    } catch (error: any) {
        if (error.code === 'auth/user-not-found') {
            return null;
        }
        throw error;
    }
}

export async function createUserSubscription(input: CreateUserSubscriptionInput): Promise<CreateUserSubscriptionOutput> {
  return createUserSubscriptionFlow(input);
}


const createUserSubscriptionFlow = ai.defineFlow(
  {
    name: 'createUserSubscriptionFlow',
    inputSchema: CreateUserSubscriptionInputSchema,
    outputSchema: CreateUserSubscriptionOutputSchema,
  },
  async (input) => {
    const accessToken = process.env.NEXT_PUBLIC_MERCADO_PAGO_ACCESS_TOKEN;
    const planId = process.env.NEXT_PUBLIC_MERCADO_PAGO_PLAN_ID;

    if (!accessToken || !planId) {
      console.error("Mercado Pago environment variables (ACCESS_TOKEN or PLAN_ID) are not configured.");
      return { success: false, error: "Server configuration error." };
    }

    const user = await getFirebaseUserByEmail(input.payer_email);
    if (!user) {
      console.error("No Firebase user found for email:", input.payer_email);
      return { success: false, error: "User not found." };
    }

    const payload = {
      preapproval_plan_id: planId,
      reason: `Assinatura Mensal FinTrack - ${user.uid}`,
      external_reference: `fintrack-user-${user.uid}-${Date.now()}`,
      payer_email: input.payer_email,
      card_token_id: input.token,
      auto_recurring: {
        frequency: 1,
        frequency_type: "months",
        transaction_amount: 39.90,
        currency_id: "BRL"
      },
      back_url: "https://fintrack-beta.vercel.app/", // Should match your app's URL
      status: "authorized"
    };

    console.log("Sending subscription payload to Mercado Pago:", JSON.stringify(payload, null, 2));

    try {
      const response = await fetch('https://api.mercadopago.com/preapproval', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${accessToken}`,
          'X-Idempotency-Key': `fintrack-sub-${user.uid}-${Date.now()}` // Unique key for each attempt
        },
        body: JSON.stringify(payload)
      });

      const responseData = await response.json();
      
      if (!response.ok) {
        console.error("Mercado Pago API Error:", responseData);
        const errorMessage = responseData.message || 'Payment rejected by Mercado Pago.';
        return { success: false, error: errorMessage };
      }

      console.log("Mercado Pago API Success Response:", responseData);

      if (responseData.status !== 'authorized') {
         return { success: false, error: `Subscription status is '${responseData.status}'. Please try another card.` };
      }

      // Update user document in Firestore on success
      const db = getFirestore(adminApp);
      const userDocRef = db.collection('users').doc(user.uid);
      const newSubscriptionEndDate = new Date();
      newSubscriptionEndDate.setMonth(newSubscriptionEndDate.getMonth() + 1);

      await userDocRef.update({
        subscriptionStatus: 'active',
        subscriptionEndDate: Timestamp.fromDate(newSubscriptionEndDate),
        mercadoPagoSubscriptionId: responseData.id,
        updatedAt: Timestamp.now(),
      });
      
      console.log("Successfully updated user subscription status in Firestore for user:", user.uid);

      return { success: true, subscriptionId: responseData.id };

    } catch (error: any) {
      console.error("Error in createUserSubscriptionFlow:", error);
      return { success: false, error: "An unexpected error occurred while processing your subscription." };
    }
  }
);
