
'use server';
/**
 * @fileOverview A Genkit flow to create a user subscription via Mercado Pago.
 *
 * - createUserSubscription - Creates a subscription for a user.
 * - CreateUserSubscriptionInput - The input type for the flow.
 * - CreateUserSubscriptionOutput - The return type for the flow.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';
import { v4 as uuidv4 } from 'uuid'; // Import UUID for idempotency key


const CreateUserSubscriptionInputSchema = z.object({
  token: z.string().describe("The card token generated by Mercado Pago's frontend."),
  issuer_id: z.string().describe("The card issuer ID."),
  payment_method_id: z.string().describe("The payment method ID (e.g., 'visa')."),
  installments: z.number().describe("The number of installments."),
  payer_email: z.string().email().describe("The email of the user paying."),
  userId: z.string().describe("The Firebase Auth User ID."),
});
export type CreateUserSubscriptionInput = z.infer<typeof CreateUserSubscriptionInputSchema>;

const CreateUserSubscriptionOutputSchema = z.object({
  success: z.boolean(),
  subscriptionId: z.string().optional(),
  init_point: z.string().optional(),
  error: z.string().optional(),
});
export type CreateUserSubscriptionOutput = z.infer<typeof CreateUserSubscriptionOutputSchema>;


export async function createUserSubscription(input: CreateUserSubscriptionInput): Promise<CreateUserSubscriptionOutput> {
  return createUserSubscriptionFlow(input);
}


const createUserSubscriptionFlow = ai.defineFlow(
  {
    name: 'createUserSubscriptionFlow',
    inputSchema: CreateUserSubscriptionInputSchema,
    outputSchema: CreateUserSubscriptionOutputSchema,
  },
  async (input) => {
    const accessToken = "TEST-4997780561675232-062608-6e8858e1e9c8d426726877731ec0dbe0-2519291532";
    const planId = "2c938084979341770197acaba53a0a05";

    const startDate = new Date();
    const endDate = new Date();
    endDate.setFullYear(endDate.getFullYear() + 1); // Subscription valid for 1 year

    const payload = {
      preapproval_plan_id: planId,
      reason: "Assinatura Fintrack",
      external_reference: `fintrack-user-${input.userId}-${Date.now()}`,
      payer_email: input.payer_email,
      card_token_id: input.token,
      auto_recurring: {
        frequency: 1,
        frequency_type: "months",
        start_date: startDate.toISOString(),
        end_date: endDate.toISOString(),
        transaction_amount: 19.99,
        currency_id: "BRL"
      },
      back_url: "https://www.castromanagement.com",
      status: "authorized"
    };

    console.log("Sending subscription payload to Mercado Pago:", JSON.stringify(payload, null, 2));

    try {
      const response = await fetch('https://api.mercadopago.com/preapproval', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${accessToken}`,
          'X-Idempotency-Key': uuidv4() // Use UUID for idempotency
        },
        body: JSON.stringify(payload)
      });

      const responseData = await response.json();
      
      if (!response.ok) {
        console.error("Mercado Pago API Error:", responseData);
        const errorMessage = responseData.message || 'Payment rejected by Mercado Pago.';
        return { success: false, error: errorMessage };
      }

      console.log("Mercado Pago API Success Response:", responseData);

      const checkoutUrl = responseData.init_point;
      
      // Firestore update logic can be re-enabled here once Firebase Admin is configured.
      // For now, the successful payment will redirect or return success.

      return { success: true, subscriptionId: responseData.id, init_point: checkoutUrl };

    } catch (error: any) {
      console.error("Error in createUserSubscriptionFlow:", error);
      return { success: false, error: "An unexpected error occurred while processing your subscription." };
    }
  }
);
