
'use server';
/**
 * @fileOverview A server action to create a user subscription via Mercado Pago.
 *
 * - createUserSubscription - Creates a subscription for a user.
 * - CreateUserSubscriptionInput - The input type for the function.
 * - CreateUserSubscriptionOutput - The return type for the function.
 */

import { z } from 'zod';
import { v4 as uuidv4 } from 'uuid';

const CreateUserSubscriptionInputSchema = z.object({
  token: z.string().describe("The card token generated by Mercado Pago's frontend."),
  payer_email: z.string().email().describe("The email of the user paying."),
  userId: z.string().describe("The Firebase Auth User ID."),
});
export type CreateUserSubscriptionInput = z.infer<typeof CreateUserSubscriptionInputSchema>;

const CreateUserSubscriptionOutputSchema = z.object({
  success: z.boolean(),
  subscriptionId: z.string().optional(),
  init_point: z.string().optional(),
  error: z.string().optional(),
});
export type CreateUserSubscriptionOutput = z.infer<typeof CreateUserSubscriptionOutputSchema>;


export async function createUserSubscription(input: CreateUserSubscriptionInput): Promise<CreateUserSubscriptionOutput> {
    const accessToken = process.env.MERCADOPAGO_ACCESS_TOKEN;
    const planId = "2c938084979341770197aedb92ad0b27";

    if (!accessToken) {
        console.error("CRITICAL: MERCADOPAGO_ACCESS_TOKEN is not defined in the environment.");
        return { success: false, error: "Server payment configuration is missing." };
    }

    const payload = {
      preapproval_plan_id: planId,
      reason: "Assinatura Fintrack",
      external_reference: input.userId, // SIMPLIFIED: Use only the user ID
      payer_email: input.payer_email,
      card_token_id: input.token,
      back_url: "https://www.castromanagement.com", // A success URL
      status: "authorized"
    };

    console.log("Sending subscription payload to Mercado Pago:", JSON.stringify(payload, null, 2));

    try {
      const response = await fetch('https://api.mercadopago.com/preapproval', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${accessToken}`,
          'X-Idempotency-Key': uuidv4()
        },
        body: JSON.stringify(payload)
      });

      const responseData = await response.json();
      
      if (!response.ok) {
        console.error("Mercado Pago API Error:", responseData);
        const errorMessage = responseData.message || 'Payment rejected by Mercado Pago.';
        return { success: false, error: errorMessage };
      }

      console.log("Mercado Pago API Success Response:", responseData);

      const checkoutUrl = responseData.init_point;
      
      return { success: true, subscriptionId: responseData.id, init_point: checkoutUrl };

    } catch (error: any) {
      console.error("Error in createUserSubscription:", error);
      return { success: false, error: "An unexpected error occurred while processing your subscription." };
    }
}
